### ISSUE TITLE
Self-executing bundling problem

### ISSUE THREAD

**Issue by tpluscode** [Hypercubed/systemjs-plugin-html#11]
Hi. I've found that when bundling with `jspm bundle-sfx`, the plugin produces calls to `System.register` for each bundled HTML file. 

```
System.register('some-doc.html!github:Hypercubed/systemjs-plugin-html@0.0.8.js', [], false, function() {});
```

When used without `system.js`, these bundles fail unless I _polyfill_ that function if it doesn't exist to avoid JS error like.

```
var System = System || {};
System.register = System.register || function() {};
```

Instead, the plugin should use the microloader emitted by the bundler: `$__System`

**Comment by tpluscode** [comment]
Or maybe just skip those `register` calls altogether when creating a self-executing bundle?

**Comment by Hypercubed** [comment]
Sorry this isn't working for you.  The SystemJS plugin system has changed a lot since I wrote this.  I need to look at this deeply, also considering that jspm v0.17 is coming soon.

**Comment by Hypercubed** [comment]
Please give the #dev branch a try.  I believe this fixes both issues.

**Comment by tpluscode** [comment]
I installed from dev branch and got this error:

> err  Error: ENOENT: no such file or directory, open 'E:\github\tpluscode\md-ed\@node\vulcanize.js'
>             at Error (native)
>         Error loading E:/github/tpluscode/md-ed/@node/vulcanize.js as "@node/vulcanize" from E:/github/tpluscode/md-ed/jspm_packages/github/Hypercubed/systemjs-plugin-html@dev/html-builder.js

Vulcanize is not there at all. Weirdly enough, installing it yields some timeouts

**Comment by Hypercubed** [comment]
Which version of JSON are you using?

**Comment by Hypercubed** [comment]
_JSPM_

**Comment by tpluscode** [comment]
0.16.33

**Comment by Hypercubed** [comment]
Can you upgrade to the latest v0.16 (.42 I beleive) and update the loader files (`jspm dl-loader`)?  You will also need to `npm install vulcanize`.  I may have broken the error message.

**Comment by tpluscode** [comment]
With newer jspm, the vulcanize error is more meaningful.

Indeed I also had to install vulcanize and additionally es6-promise and mkdirp. Why weren't these necessary before?

**Comment by tpluscode** [comment]
Anyway, the dev branch does indeed fix this issue. Thanks a lot.

**Comment by Hypercubed** [comment]
I think technically these should be peer dependencies...   But that is something not supported untill jspm v0.17.  Maybe @guybedford can help?  The jspm/SystemJS eco changes rapidly, it's hard to keep up.
