### ISSUE TITLE
Does this work for angularjs templates?

### ISSUE THREAD

**Issue by ghost** [Hypercubed/systemjs-plugin-html#5]
I'm using jspm@beta. Currently I use angular-templatecache to compile html templates. Would this plugin replace the need for that?

**Comment by Hypercubed** [comment]
I think the answer is no.  This plugin does HTML imports (via link tags).  

What exactly do you what to import?  Do you want to import the raw HTML file and have it placed into a `script type="text/ng-template"`?  This might be something that could be made into a new systemjs plugin.

Or are you looking to import a file that is the output of gulp-angular-templatecache (or similar) that already is a collection of `script type="text/ng-template"` elements?

**Comment by ghost** [comment]
I would like to import raw html and have it placed into a `script type="text/ng-template"`

Perferably SystemJS will be able to bundle all of the html imports into a templates.js file for bundling.

**Comment by Hypercubed** [comment]
I think it is possible and likely simpler than the HTML imports I am doing here.  I'll give it a try when I get time...  unless someone else gets to it first.

**Comment by Hypercubed** [comment]
Hmmm... thinking about it more I'm not sure a plugin like this does anything useful.

At runtime I don't see any benefit to using `import 'template.html!ngTemplateCache` vs ng-include.  The result is the same (`template.html` is added to `$templateCache`).  Additionally the plugin is complicated by the fact that `script` tag "must be a descendent of the $rootElement" per angular docs.

There is some benefit at bundling but again we cannot just throw a `script` tag in the header.  You would need to create a angular module that does all the `$templateCache.put`s like `gulp-angular-templatecache`.

I think a better approach may be to use [systemjs/plugin-text](https://github.com/systemjs/plugin-text) like this:

``` js
import template from './template.html!text';

angular.module('myApp',[])
  .run(function($templateCache) {
    $templateCache.put('template.html', template);
  });
```

Thoughts?

**Comment by ghost** [comment]
@Hypercubed  For components where you don't want to use ng-include but rather `template:` 

I tried using plugin-text but it doesn't work with typescript. typescript complains it can't find a module, which is odd because the css plugin works.

**Comment by Hypercubed** [comment]
I'm not sure what you mean by "For components where you don't want to use ng-include but rather template:".  Do you mean `templateUrl` in a route?  If you import via `text` plugin, then feed to `$templateCache` it should work:

```
import somethingHTML from 'components/something/something.html!text';

angular.module('myApp',[])
  .config(function($routeProvider) {
    $routeProvider
    .when('/something', {
      templateUrl: 'components/something/template.html',
    })
  })
  .run(function($templateCache) {
    $templateCache.put('components/something/something.html', somethingHTML);
  });
```

But perhaps even better is just feeding to the template:

```
import somethingHTML from 'components/something/something.html!text';

angular.module('myApp',[])
  .config(function($routeProvider) {
    $routeProvider
    .when('/something', {
      template: somethingHTML,
    })
  });
```

Actually I think that is pretty cool!

**Comment by ghost** [comment]
I tried it but typescript doesn't like `import somethingHTML from 'components/something/something.html!text';` complains it can't find a module.

`import  'components/something/something.html!text';`
would work but not usable since I can't assign it to anything.

**Comment by Hypercubed** [comment]
I'm doing exactly that and it is working for me.  Does it say what is not found (`components/something/something.html` or `text`).  Did you install the text plugin with the `text` alias?

```
jspm install text=github:systemjs/plugin-text
```

Edit: could be TypeScript, I'm not using it.

**Comment by brettstack** [comment]
Just came here to recommend trying plugin-text. I'll be trying this approach shortly with Babel. Good to hear you've had success with it, @Hypercubed. @robertbaker open an issue at plugin-text and see if they can get it working with Typescript.

**Comment by Hypercubed** [comment]
Injecting the html directly into the route template property (after reading using the text plugin) seam to work well, and bundles without issue.  If a file is missing you get an error at bundle time (which is a good thing).  Also, I do the bundling after running `gulp-minify-html` so the bundle is compact.

I wonder if anyone else is doing this.  This is all not relevant to systemjs-plugin-html but still useful discussion.  It would be great to share outside this issue.

**Comment by ghost** [comment]
I posted an issue to TypeScript and text plugin. Hopefully I can utilize it
soon. One less step in my build tasks. Now if there was only a less/sass
system js plugin

**Comment by Hypercubed** [comment]
This was a good discussion.  I summarized parts of it in this gist: https://gist.github.com/Hypercubed/356e5f9cb356bfdfa721

Thanks, closing now.

**Comment by CxRes** [comment]
I am a few years late to the party but I wonder if you could do something like this:
```
angular.module('myApp',[]).
  directive(randomDirective, function() {
    return {
      templateUrl: System.resolveSync('./random.tpl.html'),
      restrict: 'E',
      scope: {},
  };
});
```
then build it like:
```
var builder = new jspm.Builder();
builder.bundle('./**/*.tpl.html', ./bundle.html);
```
and then include `bundle.html` in your production `index.html`.

Thoughts?
