### ISSUE TITLE
Incorrect warning or dependency loading...

### ISSUE THREAD

**Issue by CxRes** [Hypercubed/systemjs-plugin-html#8]
When this plugin cannot find Vulcanize it throws the message

```
[Error: Install Polymer/vulcanize via `jspm install npm:vulcanize` for HTML build support. 
Set System.buildHTML = false to skip HTML builds.]
```

This was despite the fact that I had installed Vulcanize using JSPM. 

On a little digging I found that the plugin code in `html-builder.js` uses `var Vulcan = System._nodeRequire('vulcanize');`. This would mean that dependency must be pulled in from npm as of now.

So either this should change to `import 'vulcanize'` or `require('vulcanize')`, so that dep is changed to JSPM one or the warning message should change!

**Comment by Hypercubed** [comment]
I was having some difficult with the vulcanizing during build.  I think I have it working now and the correct message show (should be `npm install vulcanize`).  Thank you for reporting.
