### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by 212361828** [Hypercubed/systemjs-plugin-html#9]
Thanks for this.  Very interested in using it.  QQ, will you be regression testing this agains latest jspm/systemjs releases?  The readme says jspm v0.15.7, which makes me think maybe not.

**Comment by Hypercubed** [comment]
I would like to keep this up-to-date, however, both HTML imports and systemjs are changing so quickly I may have a hard time.  I do my best.

**Comment by 212361828** [comment]
Ok, thanks again!
